name: Generate Top Languages Badge

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: amitsingh-007/github-readme-stats-action@v1.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          username: AndersonMeloo
          output: top-langs.svg
          theme: dark
